# Uncomment to enable encoder
# CONFIG_EC11=y
# CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

CONFIG_ZMK_DISPLAY=y
# CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y

# if nice!view is only installed to the main side 
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
# Optional nice-view-gem settings (uncomment to customize)
# CONFIG_NICE_VIEW_GEM_WPM_FIXED_RANGE=y
# CONFIG_NICE_VIEW_GEM_WPM_FIXED_RANGE_MAX=100
# CONFIG_NICE_VIEW_GEM_ANIMATION=y
# CONFIG_NICE_VIEW_GEM_ANIMATION_MS=960
